#!/usr/bin/python3

def range_factors(num):
    dic = {100000:10000000000, 10000:1000000000, 1000:100000000,
           10000:10000000, 1000:1000000, 100:100000, 10:10000}
    for k in dic:
        flag = 0
        if dic[k] <= num:
            flag = 1
            lst = list(range(num//k, num//(k-2)))
            break
    if flag == 0:
        lst = list(range(num))
    print(lst)
    return lst


def factorize_using_cmd():
    from time import time
    from sys import argv
    from decimal import Decimal

    start = time()
    if len(argv) != 2:
        print("\aPlease add a file name as argument.\n\n")
    else:
        try:
            with open(argv[1]) as f:
                lst = f.readlines()
        except FileNotFoundError:
            print("\aFile not found.\n\n")
            exit()
        lst = [Decimal(num) for num in lst]
        for num in lst:
            normal_factors = [Decimal(f) for f in range(int(num/2), int(num))]

            for fact in normal_factors:
                if time() - start >= 5:
                    print("\aTime limit exceded.\n\n")
                    break
                if not num % fact:
                    print("{:s}={:s}*{:s}".format(str(num),
                                                  str(fact),
                                                  str(num / fact)))
                    break
            # print(f"{num}={int(num/fact)}*{fact}")


if __name__ == "__main__":
    factorize_using_cmd()
    # range_factors(14692)
