#!/usr/bin/python3

def factorize_using_cmd():
    from time import time
    from sys import argv

    start = time()
    if len(argv) != 2:
        print("\aPlease add a file name as argument.\n\n")
    else:
        try:
            with open(argv[1]) as f:
                lst = f.readlines()
        except:
            print("\aFile not found.\n\n")
            exit()
        lst = [int(num) for num in lst]
        for num in lst:
            normal_factors = list(range(2, 101)) + list(reversed(
                                                    range(int(num ** .5)-999,
                                                          int(num ** .5)+1)))
            for fact in normal_factors:
                if time() - start >= 5:
                    print("\aTime limit exceded.\n\n")
                    exit()
                if not num % fact:
                    break
            print("{:d}={:d}*{:d}".format(num, int(num / fact), fact))


if __name__ == "__main__":
    factorize_using_cmd()
